### ISSUE TITLE
Pressing "Add" is not adding closure

### ISSUE THREAD

**Issue by jm6087** [jm6087/wme-closure-helper#10]
When I click on the "Add" button, the closure is not applying. I tested with single segment select and multiple segments selected, also one-way and two-way. 

![GIF](https://user-images.githubusercontent.com/24948653/89889152-ced71180-db96-11ea-978b-63131a3899dc.gif)

**Comment by jm6087** [comment]
Found bug and reported solution in Discord

**Comment by cbrxyz** [comment]
Thanks again for your help! Fixed in db75ccc3e6bcc638920eebbb869c95113a2091b2.
