### ISSUE TITLE
Event is not listed

### ISSUE THREAD

**Issue by jm6087** [jm6087/wme-closure-helper#11]
This GIF shows that "Crash 1.5hr" preset has nothing in the MTE Search Field
When I select a segment and press the "Crash 1.5hr" preset button, the "Events" box is blank.

It then shows that the "Crash 3hr" preset had nothing in the MTE Search Field.
I entered "Roadworks" (took 3 times to stick)
When I select the segment and press the "Crash 3hr" preset button, the "Events" box is blank.

Then I show the same segment in incognito to show that there are Events listed, including "Roadworks"

My guess is that since the Events box is not filled in with something (including "None"), that may be why the RTC is not saving for me.
![GIF](https://user-images.githubusercontent.com/24948653/89890850-ab619600-db99-11ea-9ff1-d0e974b22b66.gif)

**Comment by jm6087** [comment]
Found bug and reported solution in Discord

**Comment by cbrxyz** [comment]
Fixed in db75ccc3e6bcc638920eebbb869c95113a2091b2.
