### ISSUE TITLE
Closure preset node-closing options are not working

### ISSUE THREAD

**Issue by cbrxyz** [jm6087/wme-closure-helper#12]
The node closures options in the preset menu are not working.

Thanks again @jm6087!

**Comment by jm6087** [comment]
Additional information
![image](https://user-images.githubusercontent.com/24948653/89961919-dafbb700-dc08-11ea-8ef6-5e65819aaaa1.png)

**Comment by jm6087** [comment]
Additional information.  Direction is not working either
GIF shows that preset "Crash 1.5hr" has "ALL" nodes preset and Direction B>A
I then select 2 segments and pressed the Crash 1.5hr clicksaver closure button
You can see that only the middle nodes closed (not ALL)
and the direction is 2way (not B>A)
![GIF](https://user-images.githubusercontent.com/24948653/89962558-a8eb5480-dc0a-11ea-87c6-edfe8a400543.gif)

**Comment by jm6087** [comment]
Think I figured out this issue

For the nodes issue:

`var nodeClosuresOption = $("#wmechDropdown" + (ruleIndex + 1) + "Nodes").val();`
needs to be
`var nodeClosuresOption = $("#wmech_preset" + (ruleIndex + 1) + "nodes").val();`

and for the direction issue:
`var direction = $("#wmechDropdown" + (ruleIndex + 1) + "Direction").val();`
needs to be
`var direction = $("#wmech_preset" + (ruleIndex + 1) + "direction").val();`

When I made these two changes, the preset node and direction began working as expected.

**Comment by cbrxyz** [comment]
Added to v1.0.0-beta.6, thanks again for all of your help :D 🥇

**Comment by jm6087** [comment]
You still need to do more research on the direction.  
Preset Crash 1.5hr has A>B set.  When I click on Crash 1.5hr, it shows that it is going to set it to A>B but when I save it is set as 2way
![GIF](https://user-images.githubusercontent.com/24948653/89966536-02588100-dc15-11ea-94b1-efc1f56fb3c5.gif)

**Comment by cbrxyz** [comment]
Yep, I'm seeing what you're seeing. Looking into it

**Comment by cbrxyz** [comment]
Fixed. Forgot to add the `change()` function on the direction input. That allows WME to detect that the input has successfully changed.

```js
// before
$("#closure_direction").val(dirNumber);
// after
$("#closure_direction").val(dirNumber).change();
```
