### ISSUE TITLE
Add Primary Street On "Street" Type Substitution

### ISSUE THREAD

**Issue by willdanneriv** [jm6087/wme-closure-helper#25]
Primary Street should probably be of "Street" type substitution.

![image](https://user-images.githubusercontent.com/5582060/89966435-21f3a780-dc1d-11ea-96a4-1dfe04ae38ba.png)
![image](https://user-images.githubusercontent.com/5582060/89966510-523b4600-dc1d-11ea-971d-70d933cb15a1.png)

**Comment by cbrxyz** [comment]
Thanks Will! Got that added in v1.0.0-beta.6. 👍

**Comment by cbrxyz** [comment]
Documentation is updated for this now
