### ISSUE TITLE
Incorrect information on Formatting tab?

### ISSUE THREAD

**Issue by jm6087** [jm6087/wme-closure-helper#38]
The users guide shows
![image](https://user-images.githubusercontent.com/24948653/90202854-855c1180-dda4-11ea-82c1-fafef5589b13.png)

The formatting tab in WME shows
![image](https://user-images.githubusercontent.com/24948653/90202886-9c9aff00-dda4-11ea-9010-4338a5f41ce1.png)

When I tested, {{reason}} did not do anything

**Comment by cbrxyz** [comment]
Correct, forgot to remove that

**Comment by cbrxyz** [comment]
Fixed in 4cb9278.
