### ISSUE TITLE
Handle {{type}} for multiple segments

### ISSUE THREAD

**Issue by jm6087** [jm6087/wme-closure-helper#39]
When you select a single road type, with a Name String of "{{type}} Closed", it works as described.
![image](https://user-images.githubusercontent.com/24948653/90203482-7ece9980-dda6-11ea-8db8-15b90cc359e3.png)

If I select 2 different road types (example - PS and mH or mH and MH), I get
![image](https://user-images.githubusercontent.com/24948653/90203585-bd645400-dda6-11ea-8626-f1a91f718d6f.png)

Not sure what the solution is.  A couple thoughts for when there are multiple road types selected, 
1. Ignore {{type}}
2. Choose only one {{type}} - preferably highest road type
3. Combine road types into {{type}} - I.E. mH & MH returns "Highway Closed"   PS & mH returns " Highway and Street Closed"

Side note:  I was confused by the title "Name String" and was thinking it went in the Name field.  Maybe it can be called "Description String" 
Your documentation is pretty clear, but the Formatting tab was not clear.

**Comment by cbrxyz** [comment]
Split this issue into #39 and #40

A simple {{type}} = "Roads" might work for now.

**Comment by jm6087** [comment]
I like that idea

**Comment by cbrxyz** [comment]
Fixed in 4cb9278.
