### ISSUE TITLE
Remove RegExp for MTEs

### ISSUE THREAD

**Issue by jm6087** [jm6087/wme-closure-helper#43]
I created a couple MTEs.  
"MTE Regex Match 0"
"MTE Regex Match 1"

I created a preset with an MTE regex of "Regex" and Match Number 1 (side note: this field should not be zero based since many may not understand how the numbering works in JS)
![image](https://user-images.githubusercontent.com/24948653/90245577-8fa7fb00-ddf8-11ea-8142-fd89bb3d8c6a.png)

When I added a closure using the preset, the correct MTE was selected
![image](https://user-images.githubusercontent.com/24948653/90244681-dac10e80-ddf6-11ea-9944-b62bca00f1d3.png)

I then added a new MTE - "a MTE Regex Match 2".  I made no changes to my Preset

When I added a closure using the preset, the wrong MTE was selected
![image](https://user-images.githubusercontent.com/24948653/90245020-7a7e9c80-ddf7-11ea-830e-1524947ee989.png)

Additionally, if all the other MTEs that had a Regex match expire.  The preset won't select the correct MTE since the Match number is no longer available
![image](https://user-images.githubusercontent.com/24948653/90245246-ebbe4f80-ddf7-11ea-8082-7b9ba7ba4adc.png)

I am really wondering if using Regex for an MTE match is a good choice.  Since the MTE should exist, maybe it should just be an exact match.   I am not sure how to handle multiple MTE with exact same name (can be created but really should not be done because it would be confusing anyway)

**Comment by cbrxyz** [comment]
I think that's a good idea, RegExp isn't really needed in this case. MTEs aren't that complex, and can usually just refer to the MTE by name.

Will remove RegExp.
