### ISSUE TITLE
Closure details in history - like URO+

### ISSUE THREAD

**Issue by jm6087** [jm6087/wme-closure-helper#54]
@RussPA
![image](https://user-images.githubusercontent.com/24948653/91234350-a99ae500-e6f8-11ea-9f66-788ee4f928e3.png)

**Comment by cbrxyz** [comment]
Note: This feature is not going to be "perfect" in the next release. Formatting will not be the best and attribute names may not be super perfect. But it works. New, less important, issue added for that: #60.
