### ISSUE TITLE
Checkboxes do not work on Edge

### ISSUE THREAD

**Issue by cbrxyz** [jm6087/wme-closure-helper#56]
On Microsoft Edge, the checkboxes next to each closure do not appear. For example:

![Example](https://cdn.discordapp.com/attachments/742145952630177792/748619687037763584/unknown.png)

**Comment by jm6087** [comment]
I was able to get it to work for me in Edge.  The person reporting to me said they have the same version.

![image](https://user-images.githubusercontent.com/24948653/91491888-59e42700-e87a-11ea-97f1-9f814817eb83.png)

**Comment by dizzie131** [comment]
Checkboxes are working for me on Version 84.0.522.63

**Comment by cbrxyz** [comment]
Ok, closing this issue for now. Multiple people have said this works fine on Edge. Can be reopened as needed.
