### ISSUE TITLE
Add custom length extender buttons

### ISSUE THREAD

**Issue by dizzie131** [jm6087/wme-closure-helper#57]
I have a few presets set up for various times.

Depending on the location of the car crash in the rural / outback areas of Australia, the closure times may vary.
It would be great if I could use my 6h closure preset, then click a -1h button to remove 1 hour from the closure.
Currently the script is +1 hour etc only.

![image](https://user-images.githubusercontent.com/58999144/91521651-48148980-e937-11ea-9d17-de285f9883b1.png)

**Comment by cbrxyz** [comment]
Awesome, great idea!

**Comment by jm6087** [comment]
This feature is currently added in my patch version
https://github.com/jm6087/wme-closure-helper/blob/patch-1/WME%20Closure%20Helper.user.js

I have submitted a pull request for whenever fourLoop is able to return to monitoring his script.

**Comment by cbrxyz** [comment]
Merged in 07a1d183c7efb0d2d1f5c0c9402e8d724f005a0e.
