### ISSUE TITLE
Bug? Closure Length buttons flow onto next line

### ISSUE THREAD

**Issue by dizzie131** [jm6087/wme-closure-helper#58]
The buttons are too wide for the menu screen so the last button drops to the second line.
Maybe drop the +2H button? Considering the 1H button is right next to it? 

![image](https://user-images.githubusercontent.com/58999144/91521792-a2ade580-e937-11ea-92bf-ebf69ef30c92.png)

**Comment by cbrxyz** [comment]
This will be user customizable once #57 is fixed. If a user wants a lot of extender buttons, they can have them wrap over. If not, they don't have to add as many. :+1:
