### ISSUE TITLE
"End date is before start date" is a month off

### ISSUE THREAD

**Issue by cbrxyz** [jm6087/wme-closure-helper#59]
The "End date is before start date" month sees dates as one month ahead, rather than what the month actually is.

**Comment by jm6087** [comment]
I didn't check for other locations but I tested adding "-1" to the end of var startMonth and var endMonth in function closureLength() and it appeared to work.

> function closureLength() {
>         var startDate = $("#closure_startDate").val();
>         var startTime = $("#closure_startTime").val();
>         var endDate = $("#closure_endDate").val();
>         var endTime = $("#closure_endTime").val();
>         var regex = /(.*)-(.*)-(.*)/;
>         var startDateResult = regex.exec(startDate);
>         var startYear = startDateResult[1];
>         **var startMonth = startDateResult[2]-1;**
>         var startDay = startDateResult[3];
>         var endDateResult = regex.exec(endDate);
>         var endYear = endDateResult[1];
>         **var endMonth = endDateResult[2]-1;**

**Comment by cbrxyz** [comment]
Yep, implemented a fix similar to that:
```js
-        var d1 = new Date(startYear, startMonth, startDay, startHour, startMin, 0, 0);
-        var d2 = new Date(endYear, endMonth, endDay, endHour, endMin, 0, 0);
+        var d1 = new Date(startYear, parseInt(startMonth) - 1, startDay, startHour, startMin, 0, 0);
+        var d2 = new Date(endYear, parseInt(endMonth) - 1, endDay, endHour, endMin, 0, 0);
```

Thanks!
