### ISSUE TITLE
Closure extension labels need more clarity/better styling

### ISSUE THREAD

**Issue by cbrxyz** [jm6087/wme-closure-helper#6]
As @jm6087 noted, some of the closure length extension labels are not very clear. This is especially true for the 1 month extension label which can appear as "+ 10".

![Example](https://cdn.discordapp.com/attachments/742145952630177792/742558086128074813/unknown.png)

**Comment by jm6087** [comment]
Updated and much clearer
![image](https://user-images.githubusercontent.com/24948653/120578378-53777280-c3eb-11eb-98f2-8312a872a040.png)
