### ISSUE TITLE
Scrollbar disappears

### ISSUE THREAD

**Issue by willdanneriv** [jm6087/wme-closure-helper#68]
Scrollbar disappears after selecting segment.

Screengrab by jm6087
![GIF](https://user-images.githubusercontent.com/5582060/93734222-59ebf400-fba6-11ea-8674-cfb04751d7a4.gif)

**Comment by jm6087** [comment]
FYI,  I tested making the changes that are in abelter's pull request and it seems to have fixed the issue.

**Comment by cbrxyz** [comment]
It fixes the issue at hand, but creates another issue: the WMECH custom buttons are deleted every time the panel is refreshed. This was discussed in `#closure-helper-beta` on 9/13 if you want to take a look.

**Comment by jm6087** [comment]
Thanks, I remember that now that you reminded me.

**Comment by jm6087** [comment]
I am not seeing this issue anymore.  Closing bug.  Let me know if there are still issues
