### ISSUE TITLE
Time Zone Warning Appearing in General Tab

### ISSUE THREAD

**Issue by SkulllzzCode** [jm6087/wme-closure-helper#70]
Time zone warning appears in General tab after switching from adding an closure.
https://user-images.githubusercontent.com/15911542/120941926-7196e880-c6f3-11eb-9e7e-fa9340ef22cf.mp4

**Comment by jm6087** [comment]
Thanks,  I will have to look into that.  I don't even have the Time Zone setting setup for myself.  Never got around to doing it.

**Comment by jm6087** [comment]
I believe I have found the issue.  Will update in next release.

**Comment by jm6087** [comment]
![screengrab2](https://user-images.githubusercontent.com/24948653/120943232-37c5e200-c6f3-11eb-8193-7823cb77059c.gif)
